uploadPathAbsolute=false
# uploadPath=C:\\dev\\file
uploadPath=\\storage

# 구글 이메일 2단계 인증방법
# https://myaccount.google.com/
# https://accounts.google.com/b/0/SmsAuthConfig?hl=ko 
# https://accounts.google.com/b/0/SmsAuthSettings?Setup=1
# https://security.google.com/settings/security/apppasswords?pli=1

# emailAddress=
# emailPassword=

